version: 2

project_name: talon-db-operator

builds:
  - id: manager
    main: ./cmd/main.go
    binary: manager
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

dockers:
  - image_templates:
      - "ghcr.io/opentalon/talon-db-operator:{{ .Version }}-amd64"
      - "ghcr.io/opentalon/talon-db-operator:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/opentalon/talon-db-operator:latest-amd64"
    use: buildx
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/opentalon/talon-db-k8s-operator"
    goarch: amd64

  - image_templates:
      - "ghcr.io/opentalon/talon-db-operator:{{ .Version }}-arm64"
      - "ghcr.io/opentalon/talon-db-operator:{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/opentalon/talon-db-operator:latest-arm64"
    use: buildx
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/opentalon/talon-db-k8s-operator"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/opentalon/talon-db-operator:{{ .Version }}"
    image_templates:
      - "ghcr.io/opentalon/talon-db-operator:{{ .Version }}-amd64"
      - "ghcr.io/opentalon/talon-db-operator:{{ .Version }}-arm64"

  - name_template: "ghcr.io/opentalon/talon-db-operator:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/opentalon/talon-db-operator:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/opentalon/talon-db-operator:{{ .Major }}.{{ .Minor }}-arm64"

  - name_template: "ghcr.io/opentalon/talon-db-operator:latest"
    image_templates:
      - "ghcr.io/opentalon/talon-db-operator:latest-amd64"
      - "ghcr.io/opentalon/talon-db-operator:latest-arm64"

archives:
  - id: manager
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: opentalon
    name: talon-db-k8s-operator
  extra_files:
    - glob: ./talon-db-operator.crds.yaml
    - glob: ./talon-db-operator.install.yaml
