apiVersion: v1
kind: ServiceAccount
metadata:
  name: tln-db-operator-controller-manager
  namespace: tln-db-operator-system
  labels:
    app.kubernetes.io/name: tln-db-operator
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/managed-by: kustomize
